model:
  layer_num_max:
  - 64
  - 128
  - 256
  - 512
  op_type:
  - vgg
  - repvgg
  - vgg
  - vgg
  - repvgg
  stage_layer:
  - 1
  - 3
  - 10
  - 1
  stage_ratio:
  - 0.125
  - 1.0
  - 0.125
  - 0.875
  with_maxpool:
  - true
  - true
  - false
  - false
output:
  dir: ./log/55-stage-1_3_10_1-ratio-0.125_1.0_0.125_0.875-op-vgg_repvgg_vgg_vgg_repvgg-max-True_True_False_False
  epoch_print_freq: 1
  name: '55'
  print_freq: 100
  save_freq: 20
train:
  batch_size: 256
  clip_grad: 0.0
  ema_alpha: 0.0
  ema_update_period: 8
  epochs: 300
  label_smoothing: 0.1
  loss: crossentropy
  lr_scheduler:
    decay_epochs: 30
    decay_rate: 0.1
    min_lr: 1.0e-05
  no_weight_decay: rbr_dense
  optimizer:
    base_lr: 0.01
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    momentum: 0.9
    name: SGD
    repvgg_lr: 0.001
    weight_decay_param:
      base_decay: 0.0005
      echo: false
      repvgg_decay: 0.05
  start_epoch: 0
  use_l2_norm: true
  warmup_epochs: 20
  warmup_lr: 0.01
  workers: 4
val:
  batch_size: 128
  workers: 4
